services:
  app-react:
    image: nolanmlb/app-react:1.0.3
    ports:
      - "80:80"
    depends_on:
      - app-java
  app-java:
    image: nolanmlb/app-java:1.0.4
    depends_on:
      - kstoragemongo-svc
    ports:
      - "8088:8088"
    volumes:
      - myapp-java:/data
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REACT_HOST=localhost
  kstoragemongo-svc:
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  myapp-java: